### ISSUE TITLE
publish to npm

### ISSUE THREAD

**Issue by jchartrand** [digitalbazaar/credentials-v2-context#11]
Hi! Do you plan to publish this to npm in the near-ish future? Would very much like to use it in a docker build that balks at resolving it as a GitHub branch dependency.

**Comment by dlongley** [comment]
Yes, we do, however, the W3C WG that produces this context has not finalized it. Once it is considered final, we will publish this. We're optimistic for finalization to happen around the end of this month, but it could take longer depending on what happens in the WG.

**Comment by jchartrand** [comment]
Very good - thank you!

**Comment by dlongley** [comment]
Version 3.x of `@digitalbazaar/credentials-context` now includes the draft VC v2 context. This repo is likely to be archived instead of released as an npm package; we decided to include the VC v2 context in the same package (aforementioned) as the VC v1 context.

**Comment by jchartrand** [comment]
Perfect - thank you!
